project:
  type: website
  output-dir: docs

website:
  #title: "James J. Wolpe"
  navbar:
    title: false
    logo: images/logos/full_name_white.png
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: About
#      - href: recommendations.qmd
#        text: Recommendations
    right:
      - icon: github
        href: https://github.com/jameswolpe/
      - icon: linkedin
        href: https://www.linkedin.com/in/jameswolpe/
      - icon: envelope
        href: mailto:jameswolpe@gmail.com
      - icon: reddit
        href: https://www.reddit.com/user/josephjjames

  page-footer:
    left: James Wolpe 2023
    right: This website is built with {{< fa heart title="a heart" >}} and [Quarto](https://quarto.org/)

format:
  html:
    page-layout: full
    sidebar: false
    theme:
      - yellow_theme.scss
    # css: styles.css
    toc: true
