project:
  type: website
website:
  #title: "James J. Wolpe"
  navbar:
    title: false
    logo: images/logos/full_name_white.png
    logo_css: "width: 2000px;"
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: About
#      - href: recommendations.qmd
#        text: Recommendations
    right:
      - icon: github
        href: https://github.com/jameswolpe/
      - icon: linkedin
        href: https://www.linkedin.com/in/jameswolpe/
      - icon: envelope
        href: mailto:jameswolpe@gmail.com
    align: center  # Center align the logo

  page-footer:
    background: black
    left: James Wolpe 2023
    right: This website is built with {{< fa heart title="a heart" >}} and [Quarto](https://quarto.org/)

format:
  html:
    #theme: cosmo
    css: styles.css
    toc: true

editor: source
