project:
  type: website
  output-dir: docs

website:
  favicon: images/logos/jw_logo.png
  site-url: https://jameswolpe.github.io/
  google-analytics:
    tracking-id: "G-H1P8FBJXVX"
  navbar:
    title: false
    logo: images/logos/full_name_white.png
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts
      - href: references.qmd
        text: References
      - href: cv.qmd
        text: CV
    right:
      - icon: github
        href: https://github.com/jameswolpe/
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/jameswolpe/
        target: _blank
      - icon: envelope
        href: mailto:jameswolpe@gmail.com
#      - icon: reddit
#        href: https://www.reddit.com/user/josephjjames

  page-footer:
    left: James Wolpe 2023
    right: This website is built with {{< fa heart title="a heart" >}} and [Quarto](https://quarto.org/)
format:
  html:
    page-layout: full
    sidebar: false
    theme:
      - yellow_theme.scss
