---
title: ""
---

# Full CV

## {{< fa institution >}} Work Experience


<ul>  
  <h3>Attentive Mobile</h3>
  <h4>Data Analyst Intern | May 2023 – August 2023</h4>
  <ul>
  {{< fa angle-double-right >}} Conducted comprehensive Go-to-Market (GTM) analysis to evaluate a new AI product in comparison to a legacy human-operated product, utilizing the findings to define KPIs and inform decision-making
  </ul>
  <ul>
  {{< fa angle-double-right >}} Developed and maintained data-driven dashboards using Google Looker to track and visualize key performance metrics for the AI product, enabling real-time decision-making and strategic planning
  </ul> 
  <ul>
  {{< fa angle-double-right >}} Participated in weekly meetings, delivering insights and updates on the analysis and its strategic implications, effectively communicating with both technical and non-technical stakeholders
  </ul> 
</ul>

<br>


<ul>  
  <h3>Velocity Global</h3>
  <h4>Data Science Intern | May 2022 – August 2022</h4>
  <ul>
  {{< fa angle-double-right >}} Developed business intelligence (BI) solutions that enabled data-driven decision-making under the guidance of the Principal Data Scientist and the Senior Director of Business Intelligence
  </ul>
  <ul>
  {{< fa angle-double-right >}} Engineered a predictive machine learning model in Python using XGBoost to evaluate new leads, resulting in an increase of 4.5x in conversion rate for the top 20% of scorers
  </ul> 
  <ul>
  {{< fa angle-double-right >}} Synthesized queried data from a data warehouse using SQL, identified key attributes for lead conversion from 300+ features through extensive exploratory data analysis and feature engineering
  </ul> 
</ul>

<br>

<ul>  
  <h3>Quantitative Resource Center (St. Lawrence University)</h3>
  <h4>Student Mentor | March 2022 – Present</h4>
  <ul>
  {{< fa angle-double-right >}} Tutored peers in a variety of quantitative coursework including computer science (R, Python, Java), statistics (probability, hypothesis testing), and mathematics (linear algebra, calculus)
  </ul>
  <ul>
  {{< fa angle-double-right >}} Translated technical concepts to students using clear explanations, visual aids, and hands-on demonstrations, resulting in improved understanding of the subject matter
  </ul> 
</ul>

## {{< fa institution >}} Organizations

<ul>  
  <h3>St. Lawrence Men’s Varsity Tennis</h3>
  <h4>Member (Team Captain Senior Year) | September 2019 – May 2023</h4>
  <ul>
  {{< fa angle-double-right >}} Led team as captain, chosen by coach and team members, responsible for conducting captain's practices during the offseason and fostering strong team culture; committed ~20 hours per week
  </ul>
  <ul>
  {{< fa angle-double-right >}} Served as a member of Student-Athlete Advisory Committee as an underclassman, addressing student-athlete concerns, and coordinating team participation in philanthropy events
  </ul> 
</ul>

<br>

<ul>  
  <h3>Commons College Theme House</h3>
  <h4>Resident (Head of House Senior Year) | September 2019 – May 2023</h4>
  <ul>
  {{< fa angle-double-right >}} Elected by peers as Head of House of Commons College, a co-ed living and learning community of 24 residents taking a class beyond the traditional classroom and living together
  </ul>
  <ul>
  {{< fa angle-double-right >}} Facilitated weekly house meetings, served as liaison to school administration, coordinated class with the house professor (current course is on having difficult conversations)
  </ul> 
</ul>

## {{< fa institution >}} Education

<ul>  
  <h3>St. Lawrence University</h3>
  <h4>Bachelor of Science, Data Science | Graduating December 2023</h4>
  <ul>
  {{< fa angle-double-right >}} Academic Honors: Chi Alpha Sigma (National Student-Athlete Honor Society), Mu Sigma Rho (Statistics Honor Society) Dean’s List (Summer 2021, Spring 2022), Sesquicentennial Scholarship
  </ul>
</ul>
