---
title: "CV"
---

## {{< fa briefcase >}} Work Experience


<ul>  
  <h3 style="border-bottom: none;">Attentive Mobile</h3>
  <h4>Data Analyst Intern | May 2023 – August 2023</h4>
  <ul>
  {{< fa caret-right >}} Conducted comprehensive Go-to-Market (GTM) analysis to evaluate a new AI product in comparison to a legacy human-operated product, utilizing the findings to define KPIs and inform decision-making
  </ul>
  <ul>
  {{< fa caret-right >}} Developed and maintained data-driven dashboards using Google Looker to track and visualize key performance metrics for the AI product, enabling real-time decision-making and strategic planning
  </ul> 
  <ul>
  {{< fa caret-right >}} Participated in weekly meetings, delivering insights and updates on the analysis and its strategic implications, effectively communicating with both technical and non-technical stakeholders
  </ul> 
</ul>

<br>


<ul>  
  <h3 style="border-bottom: none;">Velocity Global</h3>
  <h4>Data Science Intern | May 2022 – August 2022</h4>
  <ul>
  {{< fa caret-right >}} Developed business intelligence (BI) solutions that enabled data-driven decision-making under the guidance of the Principal Data Scientist and the Senior Director of Business Intelligence
  </ul>
  <ul>
  {{< fa caret-right >}} Engineered a predictive machine learning model in Python using XGBoost to evaluate new leads, resulting in an increase of 4.5x in conversion rate for the top 20% of scorers
  </ul> 
  <ul>
  {{< fa caret-right >}} Synthesized queried data from a data warehouse using SQL, identified key attributes for lead conversion from 300+ features through extensive exploratory data analysis and feature engineering
  </ul> 
</ul>

<br>

<ul>  
  <h3 style="border-bottom: none;">Quantitative Resource Center (St. Lawrence University)</h3>
  <h4>Student Mentor | March 2022 – Present</h4>
  <ul>
  {{< fa caret-right >}} Tutored peers in a variety of quantitative coursework including computer science (R, Python, Java), statistics (probability, hypothesis testing), and mathematics (linear algebra, calculus)
  </ul>
  <ul>
  {{< fa caret-right >}} Translated technical concepts to students using clear explanations, visual aids, and hands-on demonstrations, resulting in improved understanding of the subject matter
  </ul> 
</ul>

## {{< fa university >}} Organizations

<ul>  
  <h3 style="border-bottom: none;">St. Lawrence Men’s Varsity Tennis</h3>
  <h4>Member (Team Captain Senior Year) | September 2019 – May 2023</h4>
  <ul>
  {{< fa caret-right >}} Led team as captain, chosen by coach and team members, responsible for conducting captain's practices during the offseason and fostering strong team culture; committed ~20 hours per week
  </ul>
  <ul>
  {{< fa caret-right >}} Served as a member of Student-Athlete Advisory Committee as an underclassman, addressing student-athlete concerns, and coordinating team participation in philanthropy events
  </ul> 
</ul>

<br>

<ul>  
  <h3 style="border-bottom: none;">Commons College Theme House</h3>
  <h4>Resident (Head of House Senior Year) | June 2021 – December 2023</h4>
  <ul>
  {{< fa caret-right >}} Elected by peers as Head of House of Commons College, a co-ed living and learning community of 24 residents taking a class beyond the traditional classroom and living together
  </ul>
  <ul>
  {{< fa caret-right >}} Facilitated weekly house meetings, served as liaison to school administration, coordinated class with the house professor (current course is on having difficult conversations)
  </ul> 
</ul>

## {{< fa institution >}} Education

<ul>  
  <h3 style="border-bottom: none;">St. Lawrence University</h3>
  <h4>Bachelor of Science, Data Science | August 2019 - December 2023</h4>
  <ul>
  {{< fa caret-right >}} Academic Honors: Chi Alpha Sigma (National Student-Athlete Honor Society), Mu Sigma Rho (Statistics Honor Society) Dean’s List (Summer 2021, Spring 2022), Sesquicentennial Scholarship
  </ul>
</ul>

<br>

<ul>  
  <h3 style="border-bottom: none;">Dublin School</h3>
  <h4>September 2015 - June 2019</h4>
  <ul>
  {{< fa caret-right >}} Activities and societies: Head Tour Guide, Day Student Proctor, Boys Varsity Tennis Captain, Boys Varsity Basketball Captain
  </ul>
</ul>

## {{< fa code >}} Technical Skills

<h3 style="border-bottom: none;">Programming</h3>
<ul class="split-list">
  <li class="split-list-column">
    <ul>
      {{< fa caret-right >}} R (Tidyverse, ggplot2, Shiny)
      <br>
      {{< fa caret-right >}} SQL (Snowflake, PostgreSQL)
      <br>
      {{< fa caret-right >}} Python (Pandas, NumPy, Scikit-learn)
      <br>
      {{< fa caret-right >}} Java
      <br>
      {{< fa caret-right >}} Google Looker Studio
    </ul>
  </li>
  <li class="split-list-column">
    <ul>
      {{< fa caret-right >}} Data Visualization
      <br>
      {{< fa caret-right >}} Git (GitHub, GitLab)
      <br>
      {{< fa caret-right >}} Object-Oriented Programming
      <br>
      {{< fa caret-right >}} Database Management Systems (DBMS)
    </ul>
  </li>
</ul>

<br>
<style>
  .split-list {
    display: flex;
    justify-content: space-between;
    list-style: none;
    padding: 0;
  }

  .split-list-column {
    flex-basis: 48%; /* Adjust as needed */
  }
</style>

<h3 style="border-bottom: none;">Math & Statistics</h3>
<ul class="split-list">
  <li class="split-list-column">
    <ul>
      {{< fa caret-right >}} Probability
      <br>
      {{< fa caret-right >}} Calculus (Differential, Integral, Multivariable)
      <br>
      {{< fa caret-right >}} Statistical and Machine Learning
      <br>
      {{< fa caret-right >}} Time Series Analysis
    </ul>
  </li>
  <li class="split-list-column">
    <ul>
      {{< fa caret-right >}} Regression Analysis
      <br>
      {{< fa caret-right >}} A/B Testing
      <br>
      {{< fa caret-right >}} Linear Algebra
      <br>
      {{< fa caret-right >}} Multi-level Modeling
    </ul>
  </li>
</ul>
