---
title: "Horse Racing Market Prediction: Beat the Books"
author: "James Wolpe"
date: "5/7/2023"
categories: ["Data Science"]
affiliations: "St. Lawrence University"
---

**Author:** James Wolpe  
**Affiliation:** St. Lawrence University  
**Course:** DATA 352: Statistical and Machine Learning  
**Instructor:** Dr. Michael Schuckers  
**Date:** May 7th, 2023  
**Source:** [Wikipedia - Horse Racing](https://en.wikipedia.org/wiki/Horse_racing)

## Introduction

As the legalization of sports betting becomes more widespread, the significance and worth of predictive models that can forecast outcomes are increasingly crucial and valuable. This project explores the potential of outperforming oddsmakers and bettors in horse racing, given the hypothesis that horse race bettors make less informed bets compared to other sports.

## Background

Bill Benter's success using computer software in horse race betting serves as inspiration for this project ([source](https://norsecorp.com/horse-racing-betting-strategies/)). While not betting real money, the goal is to identify inefficiencies in horse racing betting by creating a model that predicts which horses are most likely to place in a race.

## Data Source

The data used for training the models is sourced from Kaggle, specifically the [Horse Racing Market Analysis and Prediction dataset](https://www.kaggle.com/datasets/thedevastator/horse-racing-market-analysis-and-prediction-data?datasetId=2822934&sortBy=dateRun&tab=collaboration&select=runners.csv). The comprehensive dataset contains over 43,000 observations from three months in the summer of 2016.

## Data Preparation

Out of the total 139 features, 69 were selected as potentially valuable and free from data leakage. The dataset underwent preprocessing, including filtering out incorrectly populated races and races with too many missing values. One-hot encoding and engineering the target variable "top_3" were performed, resulting in a final dataset with 79 features and ~24,000 rows.

## Exploratory Data Analysis

Initial exploratory data analysis revealed that the performance of horses in their last three races had the highest correlation with whether or not the horse placed in the race.

## Model Building

Three models were fitted: a Random Forest model, a Logistic Regression model, and a Neural Network. The Random Forest outperformed the others, achieving an accuracy score of 0.718398, beating seven of the eight tipsters.

### Random Forest Model

Confusion Matrix:
